---
title: "Team Tesla"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    horizontal_layout: fill
    css: styles.css
    theme:
      version: 5
      navbar-bg: "#3ADAC6"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
---
---

```{r setup, include=FALSE}
library(flexdashboard)
thematic::thematic_rmd(font = "auto")
```

Table{data-icon="fa-table"}
===
Row
-----------------------------------------------------------------------

### Cars Sold

```{r}
df<-read.csv("ElectricCarData_Clean.csv")
valueBox(nrow(df), icon = "fa-car")
```

### Total Sales in $

```{r}
valueBox(sum(df[, 'PriceEuro'], na.rm = TRUE), icon = "fa-money", color="#85bb65")
```

### Brands

```{r}
valueBox(length(unique(df$Brand)), icon = "fa-tag")
```

### Models

```{r}
valueBox(length(unique(df$Model)), icon = "fa-cubes")
```

### Mean Price of Car (in $)

```{r}
valueBox(trunc(mean(df$PriceEuro)), icon = "fa-dollar",color = "green")
```

### Mean Range (in Kms)

```{r}
valueBox(trunc(mean(df$Range_Km)), icon = "fas fa-car-battery", color="#f8c294")
```

Column  {data-width=1200}
-----------------------------------------------------------------------
### Data

```{r}
library(DT)
# Show table using DT package
df<-read.csv("ElectricCarData_Clean.csv")
DT::datatable(df,options = list(),fillContainer = FALSE)
```

Market Trends{data-icon="fa-bar-chart"}
===
Column {data-width=600}
-----------------------------------------------------------------------

### Cars by Features

```{r}
library(plotly)

data<-read.csv("ElectricCarData_Clean.csv")
fig <- plot_ly(data,x =~Brand,y =~Seats,z =~Segment,color=~Brand,hovertemplate = ~paste('Brand:', Brand, '<br>Seats:', Seats, '<br>Segment:', Segment,"<br><b>Model</b>: ",Model))
fig <- fig %>% add_markers()
fig <- fig %>% layout(title='Brands vs. Segment vs. Seats',scene = list(xaxis = list(title = 'Brand'),
                                   yaxis = list(title = 'Seats'),
                                   zaxis = list(title = 'Segment')))

fig
```

Column {data-width=400}
-----------------------------------------------------------------------

### Market Domination by Company

```{r}
library(plotly)
df <- data.frame(read.csv("ElectricCarData_Clean.csv", header=TRUE,sep=","))

data <- df[,c('Brand', 'PriceEuro','Model')]
fig <- plot_ly(data, labels =~Brand, values = ~PriceEuro, type = 'pie',
               textposition = 'inside',
               textinfo = 'label+percent',
               insidetextfont = list(color = '#FFFFFF'),
               marker = list(colors = colors,line = list(color = '#FFFFFF', width = 1), pull=1.5),
               showlegend = FALSE)
fig <- fig %>% layout( title='% by Brand',
                       xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                       yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig
```

### Rapid Charging

```{r}
fig <- plot_ly(df, x=~RapidCharge,y = ~PriceEuro,color =~RapidCharge, type = "box", boxpoints = "all", jitter = 0.3,
               pointpos = -1.8)

fig
```

Feature Comparsion{data-icon="fa-car"}
===
Column {data-width=500}
-----------------------------------------------------------------------

### Fastest Charging/KmH

```{r}
fig <- plot_ly(df, x = ~Brand, y = ~FastCharge_KmH, type = 'scatter',text = ~paste("Model: ",Model))

fig
```

Column {data-width=500}
-----------------------------------------------------------------------

### Fastest Acceleration

```{r}
fig <- plot_ly(
  df, x = ~Brand, y = ~AccelSec,
  color = ~AccelSec,hovertemplate = ~paste("<b>Model</b>: ",Model,"<br><b>Acceleration/Sec:</b>",AccelSec))

fig
```

### Highest Price
```{r}
fig <- plot_ly(df, x = ~Brand, y = ~PriceEuro, type = 'scatter', mode = 'markers',color='Inferno',
  # Hover text:
  text = ~paste("Model: ",Model))
               
fig
```

Range vs Speed{data-icon="fa-bolt"}
===
Column {data-width=600}
-----------------------------------------------------------------------
### Highest Range/km
```{r}
fig <- plot_ly(
  df, x = ~Brand, y = ~Range_Km, type='scatter',mode = 'markers',
  # Hover text:
  text = ~paste("<b>Model</b>: ",Model,"<br>RapidCharge: ",RapidCharge, '<br>Price: $',PriceEuro),
  color = ~Brand, size = ~Seats
)
fig
```

### Highest Speed
```{r}
fig <- plot_ly(df, x = ~Brand, y = ~TopSpeed_KmH, color = ~TopSpeed_KmH, size = ~TopSpeed_KmH,hovertemplate = ~paste("<b>Model</b>: ",Model,"<br>TopSpeed_KmH: ",TopSpeed_KmH))

fig
```
